kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    # avp.kubernetes.io/path: projects/27803622623/secrets/test-secret
    # avp.kubernetes.io/secret-version: "latest"
type: Opaque
data:
  REDIS_URL: <path:projects/27803622623/secrets/test-secret#test-secret | jsonPath {.REDIS_URL} | base64encode>
  # REDIS_URL: <test-secret | jsonPath {.REDIS_URL}>
