kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/27803622623/secrets/test-secret
    avp.kubernetes.io/secret-version: "latest"
type: Opaque
stringData:
  # REDIS_URL: <path:projects/27803622623/secrets/test-secret#test-secret | jsonPath {.REDIS_URL}>
  REDIS_URL: <test-secret | jsonPath {.STAGING.REDIS_URL}>
