kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/27803622623/secrets/test-secret
    avp.kubernetes.io/secret-version: "latest"
type: Opaque
stringData:
  password: <test-secret | jsonPath {.username}>
