kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/27803622623/secrets/circleci-token
    avp.kubernetes.io/secret-version: "latest"
type: Opaque
data:
  password1: <circleci-token>
