kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: projects/27803622623/secrets/notablejworker-deploy
    avp.kubernetes.io/secret-version: "latest"
type: Opaque
stringData:
  REDIS_URL: <notablejworker-deploy | jsonPath {.STAGING.REDIS_URL}>
